apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: exam-app
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      containers:
      - name: exam-container
        image: my-image:latest